# Name of the model to be used or saved
MODEL_NAME: "BNN_TL"
MODEL_NAME_MF: "BNN_MF"
MODEL_NAME_LF: "BNN_LF"
MODEL_NAME_CK: "CoKriging"

# Mean (mu) for the prior distribution in the Bayesian layers of the low-fidelity/TL model
MU: 0
# Mean (mu) for the prior distribution in the Bayesian layers of the mid-fidelity model
MU_MF: 0
# Standard deviation (std) for the prior distribution in the Bayesian layers of the low-fidelity/TL model
STD: 0.0351
# Standard deviation (std) for the prior distribution in the Bayesian layers of the mid-fidelity model
STD_MF: 0.1176
# Architecture of the low-fidelity/TL model, specifying the number of units in each hidden layer
UNITS: [224, 144, 160, 112, 96]
# Architecture of the mid-fidelity model, specifying the number of units in each hidden layer
UNITS_MF: [64, 64, 64]
# Device on which the model will be trained (e.g., "cpu", "cuda" for GPU)
DEVICE: "cpu"
# Random seed for reproducibility
SEED: 42